// Generated by https://quicktype.io

export interface Metrics {
    data: Data;
}

export interface Data {
    items: Item[];
}

export interface Item {
    symbol:                                         string;
    "implied-volatility-index":                     string;
    "implied-volatility-index-5-day-change":        string;
    "implied-volatility-index-rank":                string;
    "tos-implied-volatility-index-rank":            string;
    "tw-implied-volatility-index-rank":             string;
    "tos-implied-volatility-index-rank-updated-at": string;
    "implied-volatility-index-rank-source":         string;
    "implied-volatility-percentile":                string;
    "implied-volatility-updated-at":                string;
    "liquidity-value":                              string;
    "liquidity-rank":                               string;
    "liquidity-rating":                             number;
    "created-at":                                   string;
    "updated-at":                                   string;
    "option-expiration-implied-volatilities":       OptionExpirationImpliedVolatility[];
    "liquidity-running-state":                      LiquidityRunningState;
    beta:                                           string;
    "beta-updated-at":                              string;
    "corr-spy-3month":                              string;
    "dividend-rate-per-share":                      string;
    "annual-dividend-per-share":                    string;
    earnings:                                       Earnings;
    "listed-market":                                string;
    lendability:                                    string;
    "borrow-rate":                                  string;
}

export interface Earnings {
    visible:                boolean;
    "expected-report-date": string;
    estimated:              boolean;
    "late-flag":            number;
    "quarter-end-date":     string;
    "actual-eps":           string;
    "consensus-estimate":   string;
    "updated-at":           string;
}

export interface LiquidityRunningState {
    sum:          string;
    count:        number;
    "started-at": string;
    "updated-at": string;
}

export interface OptionExpirationImpliedVolatility {
    "expiration-date":    string;
    "option-chain-type":  OptionChainType;
    "settlement-type":    SettlementType;
    "implied-volatility": string;
}

export enum OptionChainType {
    Standard = "Standard",
}

export enum SettlementType {
    Pm = "PM",
}
